language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode11.5
    - os: windows
compiler:
  - clang
script:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install doxygen sphinx graphviz; fi
  - cd build && mkdir gen && cd gen
  - cmake ../..  
